### ISSUE TITLE
Live docs have wrong img class for responsive

### ISSUE THREAD

**Issue by georgiastuart** [cast-org/figuration#205]
http://figuration.org/content/figures/#content

This says you need "img-fluid" instead of "img-responsive" in figures. 

Appears to be fixed in later docs, but confusing since it's img-responsive in the current release.

**Comment by mbrambilla** [comment]
Closing, as this as this will be resolved with upcoming the v3.0.0-alpha.2 release.

Upcoming release has the renaming of `img-responsive` to `img-fluid`.
