### ISSUE TITLE
Incorrect validation styles

### ISSUE THREAD

**Issue by bgoldowsky** [cast-org/figuration#410]
Using figuration 4.0.0.alpha.4; testing in Chrome on Mac.

I'm working on making a Wicket form component that uses the validation classes to display any errors.

After validating a form and updating HTML via AJAX, I have HTML something like this:

```
<form class=”was-validated”>
<div class="col form-group">
    <label class="form-control-label">Last name</label>
    <input type="text" class="form-control is-invalid">
    <div class="invalid-feedback">'Last name' is required.</div>
</div>
</form>
```

Result looks like this:  green outline, red error message

![image](https://user-images.githubusercontent.com/2131184/55960586-1cf2a280-5c3b-11e9-8e55-01c3df8f6aa9.png)

My suspicion is that the is-invalid class should take precedence over :valid, but the opposite is happening in some cases.   Or am I doing something wrong?

**Comment by mbrambilla** [comment]
When using the `.is-{valid/invalid}` classes, don't use the `.was-validated` class on the form.

From this example, the `required` attribute may also be needed on the input field.
