### ISSUE TITLE
Top menu of the docs web-site is gigantic in Firefox

### ISSUE THREAD

**Issue by i64** [cast-org/figuration#628]
This is how the menu looks like in Chromium (menu is proportional):
![chromium](https://user-images.githubusercontent.com/37900376/85393137-02ed6900-b53c-11ea-8151-58c0964c177d.png)

In the latest Firefox on Linux the menu becomes huge (in some resolutions taking up to half of the screen space):
![firefox](https://user-images.githubusercontent.com/37900376/85393268-3c25d900-b53c-11ea-96af-07c5139bd518.png)

**Comment by mbrambilla** [comment]
Confirmed Firefox 68.7esr on CentOS 8.

**Comment by mbrambilla** [comment]
Also pushed an interim update to the online docs to resolve the issue.

**Comment by mbrambilla** [comment]
Thank you for the bug report. 👍
